# -*- coding: utf-8 -*-
"""Word Guess Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15k5T5t8Oo97MBBWKLi-PzqDLJqZO4KvC

# AIM: Write a program to implement the Hangman game using python.
"""

import random

def choose_word():
    words = ["python", "hangman", "problem", "meenu", "patel", "goal", "dsa"]
    return random.choice(words)

def display_word(word, guessed_letters):
    displayed_word = ""
    for letter in word:
        if letl
        ter in guessed_letters:
            displayed_word += letter
        else:
            displayed_word += "_"
    return displayed_word

def hangman():
    word_to_guess = choose_word()
    guessed_letters = []
    attempts = 6

    print("Welcome Meenu!")
    print("Try to guess the word.")

    while attempts > 0:
        print("\nWord:", display_word(word_to_guess, guessed_letters))
        print("Attempts left:", attempts)
        guess = input("Enter a letter: ").lower()

        if len(guess) != 1 or not guess.isalpha():
            print("Please enter a single letter.")
            continue

        if guess in guessed_letters:
            print("You've already guessed that letter.")
            continue

        guessed_letters.append(guess)

        if guess not in word_to_guess:
            print("Incorrect!")
            attempts -= 1
        else:
            print("Correct!")

        if all(letter in guessed_letters for letter in word_to_guess):
            print("\nCongratulations! You guessed the word:", word_to_guess)
            break

    if attempts == 0:
        print("\nSorry, you ran out of attempts. The word was:", word_to_guess)

hangman()